(define (smallest-divisor n)
  (define (find-divisor n test-divisor)
    (cond ((> (* test-divisor test-divisor) n) n)
          ((= (remainder n test-divisor) 0) test-divisor)
          (else (find-divisor n (next test-divisor)))))
  (define (next n)
    (if (= n 2)
        3
        (+ n 2)))
  (find-divisor n 2))
